#!/bin/bash

# Professional NVIDIA Power Optimizer Installer
# Designed for laptops with or without iGPU

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}===============================================${NC}"
echo -e "${BLUE}   NVIDIA Power Optimizer - Universal Setup    ${NC}"
echo -e "${BLUE}===============================================${NC}"

# 1. Essential Check: Detect OS Base
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_BASE="${ID_LIKE:-$ID}"
    echo -e "${BLUE}Target Base Detected: $OS_BASE${NC}"
else
    echo -e "${RED}Error: System detection failed! /etc/os-release not found.${NC}"
    exit 1
fi

# 2. Dependency Management
echo -e "${BLUE}Checking and installing dependencies...${NC}"
case "$OS_BASE" in
    *arch*)
        sudo pacman -S --noconfirm nvidia-utils power-profiles-daemon
        ;;
    *debian*|*ubuntu*)
        sudo apt update && sudo apt install -y nvidia-utils-common power-profiles-daemon
        ;;
    *fedora*|*rhel*)
        sudo dnf install -y nvidia-smi power-profiles-daemon
        ;;
    *)
        echo -e "${RED}Warning: Base '$OS_BASE' not explicitly supported for auto-install.${NC}"
        echo "Please ensure 'nvidia-smi' and 'power-profiles-daemon' are installed."
        ;;
esac

# 3. Automatic GPU Bus ID Detection
GPU_ID=$(nvidia-smi --query-gpu=pci.bus_id --format=csv,noheader | head -n1)
if [ -z "$GPU_ID" ]; then
    echo -e "${RED}Critical Error: NVIDIA GPU not detected! Verify drivers and hardware connection.${NC}"
    exit 1
fi
echo -e "${GREEN}Successfully detected GPU at Bus ID: $GPU_ID${NC}"

# 4. Generate the Core Optimizer Script
echo -e "${BLUE}Generating optimizer script at /usr/local/bin/gpu-optimizer.sh...${NC}"
cat << EOF | sudo tee /usr/local/bin/gpu-optimizer.sh > /dev/null
#!/bin/bash
# Automatically generated by NVIDIA Power Optimizer Installer

GPU_ID="$GPU_ID"
AC_STATUS=\$(cat /sys/class/power_supply/AC*/online | head -n1)

# Ensure persistence mode is on for consistent clock locking
nvidia-smi -pm 1

if [ "\$AC_STATUS" -eq 0 ]; then
    # BATTERY MODE: Throttle GPU and limit CPU power
    # Essential for laptops without iGPU to prevent thermal runaway on battery
    nvidia-smi -i \$GPU_ID -lgc 210,400
    powerprofilesctl set power-saver
else
    # AC MODE: Unlock GPU and set System to Balanced/Performance
    nvidia-smi -i \$GPU_ID -rgc
    powerprofilesctl set balanced
fi
EOF

sudo chmod +x /usr/local/bin/gpu-optimizer.sh

# 5. Create the udev Rule for Event-Driven Execution
echo -e "${BLUE}Setting up udev event listener...${NC}"
echo 'SUBSYSTEM=="power_supply", ACTION=="change", RUN+="/usr/bin/bash /usr/local/bin/gpu-optimizer.sh"' | sudo tee /etc/udev/rules.d/99-gpu-power.rules > /dev/null

# 6. Apply and Activate
echo -e "${BLUE}Activating services and rules...${NC}"
sudo systemctl enable --now power-profiles-daemon
sudo udevadm control --reload-rules
sudo udevadm trigger

echo -e "${GREEN}===============================================${NC}"
echo -e "${GREEN}   SUCCESS: Installation Complete!             ${NC}"
echo -e "${GREEN}   Your GPU will now auto-throttle on battery. ${NC}"
echo -e "${GREEN}===============================================${NC}"
